name: server
version: 1.0.0

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  args: ^2.0.0
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  functions_framework: ^0.4.1

dev_dependencies:
  build_runner: ^2.3.2
  functions_framework_builder: ^0.4.7
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.15.0